[package]
name = "pe-sign"
version = "0.1.0"
edition = "2021"

[dependencies]
cms = { version = "0.2.3", features = ["std"] }
der = { version = "0.7.9", features = ["derive"] }
pem-rfc7468 = { version = "1.0.0-rc.1", features = ["std"] }
rsa = "0.9.6"
sha1 = { version = "0.10.6", features = ["oid"] }
x509-cert = { version = "0.2.5", features = ["sct"] }
